### ISSUE TITLE
Conflicts between babel dependency versions and Node versions break jp-babel

### ISSUE THREAD

**Issue by gnestor** [n-riesco/jp-babel#10]
Follow up from https://github.com/n-riesco/jp-babel/pull/9#issuecomment-257987130

I upgraded the babel dependencies when working on https://github.com/n-riesco/jp-babel/pull/9 and encountered `You gave us a visitor for the node type "ForAwaitStatement" but it's not a valid type` when trying to use async/await in a cell. Doing a `git clean -xfd && npm install` resolved it for me.

Another issue that is somewhat related is the `Error: Module version mismatch. Expected 48, got 47.` error that occurs when jp-babel is installed with one version of Node and used with another without rebuilding. There is an open issue on ijavascript: https://github.com/n-riesco/ijavascript/issues/76

**Comment by n-riesco** [comment]
@gnestor Did the error `You gave us a visitor for the node type "ForAwaitStatement" but it's not a valid type` kill the kernel? Or the kernel just printed out the error message? If the latter, I don't think I'd be able to distinguish it from a syntax error.

**Comment by gnestor** [comment]
No, it was Babel compilation error so it did not kill the kernel...so I think essentially the same as a syntax error.

**Comment by gnestor** [comment]
StackOverflow thread about it: http://stackoverflow.com/questions/39894749/you-gave-us-a-visitor-for-the-node-type-forawaitstatement-but-its-not-a-valid

**Comment by n-riesco** [comment]
OK. I'll close this issue, since 2c7227c fixes the version mismatch error.
