### ISSUE TITLE
babel7 support

### ISSUE THREAD

**Issue by huynhnguyen** [n-riesco/jp-babel#20]
hi,
My current project requires babel7 but it seems to be not supported by jp-babel. Is there is any solution to make it works with babel 7?
I really appreciate this package, it saves a lot of my time.

**Comment by n-riesco** [comment]
@huynhnguyen I'm sorry it took me so long to address this issue.
I'm planning to release `jp-babel` v2 today (as soon as the build in Travis succeeds).
`jp-babel` v2 uses Babel 7, but note that issue #11 is still present.
