### ISSUE TITLE
Bug with import relative file paths

### ISSUE THREAD

**Issue by slavaGanzin** [n-riesco/jp-babel#5]
`import * from "module"`
Works fine and always return 'use strict', that's ok.
But `import * from "**./**module"` always fails if contains es6 features.
This should be alike with https://github.com/n-riesco/jp-coffeescript/commit/52ea3b454137cc3db4593ab43c38574743a316b8

@n-riesco I'm not familiar with babel, so I can't fix it by myself corectlly.

**Comment by n-riesco** [comment]
Issue #3 is related. Unfortunately, a solution may be more involved. In fact, the babel-repl developers seem to have given up all together on importing modules, see [this commit](https://phabricator.babeljs.io/rBC34bc8b0aea149d96d88c5777b3dea6e122c8d9bc) and [this issue](https://phabricator.babeljs.io/T6870)

I need to spend more time investigating our options. But I want to finish refactoring NEL before I address what looks like a difficult issue.

**Comment by n-riesco** [comment]
TODO
- [x] Check whether [`require("babel-register")`](https://babeljs.io/docs/usage/require/) fixes this issue.
